### ISSUE TITLE
Should _get_session be public?

### ISSUE THREAD

**Issue by frankier** [django-functest/django-functest#2]
It seems generally useful for reading sessions variables.

**Comment by spookylukey** [comment]
Given that we have `set_session_data`, which sometimes needs to do some setup work, we should probably have `get_session_data` as a public API, rather than exposing the Django session object directly - it might paint us into a corner in terms of guarantees about what happens when you `.save()` it etc.

**Comment by frankier** [comment]
Okay I'll put together a simple PR
