### ISSUE TITLE
Should `FuncWebTestMixin` expose `click()`?

### ISSUE THREAD

**Issue by duncanjbrown** [django-functest/django-functest#47]
Thanks for this great library! My question:

`django-functest` exposes a [`click()`](https://django-functest.readthedocs.io/en/latest/selenium.html#django_functest.FuncSeleniumMixin.click) method for Selenium.

`webtest` itself [also exposes a `click()` method](https://docs.pylonsproject.org/projects/webtest/en/latest/api.html#webtest.response.TestResponse.click), which likewise accepts a string to identify a link.

`FuncWebTestMixin` offers `follow_link()`, which requires a CSS selector, but it does not offer `click()`.

I'm used to writing `click_link "the text of the link"` in [`capybara`](https://github.com/teamcapybara/capybara) in Ruby. I much prefer specifying the text of the link to specifying it in CSS, because the text is what the user sees.

1. Is there a reason why `django-functest` couldn't expose a generic `click(link_text)` method in the common API, given both Selenium and WebTest offer it?
2. if this isn't possible, am I missing something in the docs which would allow me not to specify CSS when clicking a link?

**Comment by spookylukey** [comment]
Our `click()` method has quite different semantics from `WebTest`. The main reason is to distinguish it from [submit](https://django-functest.readthedocs.io/en/latest/common.html#django_functest.FuncCommonApi.submit) and [follow_link](https://django-functest.readthedocs.io/en/latest/common.html#django_functest.FuncCommonApi.follow_link). IIRC all three of these have different behaviour regarding some things like waiting for pages to reload.

I also prefer my naming because "click" assumes a mouse, rather than a touch screen, keyboard navigation or even some other input device like voice control.

However, I would be very open to these methods gaining a way of specifying the control via text, rather than a CSS selector. I think you want to add `follow_link(text=...)` which doesn't yet exist.

**Comment by duncanjbrown** [comment]
Yes — fair point about `click()` semantics! I'm not convinced that the need to discriminate between input methods is necessary for the common case, but I don't want to die on that hill — would you consider a PR attempting a `text=` argument, if I attempted!?

**Comment by spookylukey** [comment]
@duncanjbrown yes that sounds great.
